### ISSUE TITLE
PHP 8 version?

### ISSUE THREAD

**Issue by taat** [API-Skeletons/oauth2-doctrine#6]
Will this library support PHP8?

**Comment by alexz707** [comment]
hi! 
i have made a PR ( #9 ) so maybe @TomHAnderson is accepting it.
Feel free to review it!
Regards
Alex

**Comment by TomHAnderson** [comment]
I've merged your PR @alexz707 and released version 5.1.0

**Comment by TomHAnderson** [comment]
It should be noted Laminas doesn't support PHP@8.1 yet in the oauth2 library.
